import Navigation from "@/components/navigation";
import Providers from "@/components/providers";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Providers>
			<html lang="en">
				<body
					className={cn(
						"bg-zinc-100 min-h-screen font-sans antialiased",
						inter.className
					)}
				>
					<Navigation />
					{children}
				</body>
			</html>
		</Providers>
	);
}
